import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import NavBar from "@/Components/NavBar";
import Frame from "@/Components/Frame";
import { SizeContextProvider } from "@/context/resizeContext";
import { LoadingRouterProvider } from "@/Components/LoadingRouterProvider";
import GlobalLoader from "@/Components/GlobalLoader";
import { ThemeContextProvider } from "@/context/themeContext";
import CustomBody from "@/Components/CustomBody";
import AuthContextProvaider from "@/context/authContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Assets Studio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SizeContextProvider>
          <LoadingRouterProvider>
            <ThemeContextProvider>
              <AuthContextProvaider>
                <CustomBody>
                  <NavBar />
                  <GlobalLoader>
                    <Frame>{children}</Frame>
                  </GlobalLoader>
                </CustomBody>
              </AuthContextProvaider>
            </ThemeContextProvider>
          </LoadingRouterProvider>
        </SizeContextProvider>
      </body>
    </html>
  );
}
