import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import NavBar from "@/Components/NavBar";
import Frame from "@/Components/Frame";
import { SizeContextProvider } from "@/utils/resizeContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-row `}
      >
        <SizeContextProvider>
          <NavBar />
          <Frame>{children}</Frame>
        </SizeContextProvider>
      </body>
    </html>
  );
}
