export const Options = [
  { name: "Object", param: "cat-object", value: "object" },
  { name: "Character", param: "cat-character", value: "character" },
  { name: "Nature", param: "cat-nature", value: "nature" },
  { name: "Surfaces", param: "cat-surfaces", value: "surfaces" },
  { name: "Made with IA", param: "cat-ia", value: "ia" },
  { name: "Other", param: "cat-other", value: "other" },
];

export const ReportSelectorOptions = [
  { name: "Inappropriate Content", value: "InappropriateContent" },
  { name: "Spam", value: "Spam" },
  { name: "Data Error", value: "DataError" },
  { name: "Abuse", value: "Abuse" },
  { name: "Bug", value: "Bug" },
  { name: "Fraud", value: "Fraud" },
  { name: "Other", value: "other" },
];

export const keyWords = [
  "character",
  "environment",
  "object",
  "ui",
  "icon",
  "background",
  "tile",
  "sprite",
  "weapon",
  "item",
  "monster",
  "player",
  "npc",
  "fantasy",
  "sci-fi",
  "medieval",
  "modern",
  "futuristic",
  "cyberpunk",
  "space",
  "nature",
  "urban",
  "forest",
  "desert",
  "ocean",
  "mountain",
  "robot",
  "animal",
  "human",
  "alien",
  "dragon",
  "zombie",
  "ghost",
  "sword",
  "gun",
  "armor",
  "potion",
  "coin",
  "key",
  "chest",
  "food",
  "menu",
  "button",
  "healthbar",
  "minimap",
  "inventory",
  "dialog",
  "effect",
  "explosion",
  "fire",
  "water",
  "magic",
  "particle",
  "glow",
  "low-poly",
  "pixel-art",
  "cartoon",
  "realistic",
  "hand-drawn",
  "vector",
  "2d",
  "3d",
  "isometric",
  "top-down",
  "side-scroller",
  "platformer",
  "rpg",
  "shooter",
  "strategy",
  "puzzle",
  "horror",
  "adventure",
  "casual",
];
